In [4]:
# -*- coding: utf-8 -*-
from pathlib import Path
import pandas as pd
import os 

project_dir =  Path(globals()['_dh'][0]).parent
current_dir =  Path(globals()['_dh'][0])

valid_df = pd.read_csv(os.path.join(project_dir, 'notebooks/2.0-jrb-external-data-exploration/valid_set.csv'))
valid_df

                                               filename classID
0     wd\SDSSJ122257.58+300242.6_15249-59265-0059_46...     WDA
1     wd\SDSSJ012606.08+144045.9_15010-59199-0313_44...     WDA
2     wd\SDSSJ090803.30+513632.7_15174-59232-0014_43...     WDZ
3     wd\SDSSJ015221.11-003037.7_15013-59165-0159_43...     WDA
4     wd\SDSSJ084824.88+020918.5_15146-59206-0321_45...     WDA
...                                                 ...     ...
1118  wd\SDSSJ083628.20+354649.6_15062-59227-0336_45...     WDA
1119  wd\SDSSJ063256.89+171629.5_15229-59303-0400_45...     WDA
1120  wd\SDSSJ164122.52+393649.2_15309-59312-0293_51...     WDA
1121  wd\SDSSJ075645.52+272747.8_15021-59165-0078_45...     WDA
1122  wd\SDSSJ080051.54+223558.4_15051-59204-0252_45...     WDA

[1123 rows x 2 columns]

In [5]:
only_wd = valid_df.loc[valid_df['classID'] == 'WD']
only_wd

                                               filename classID
55    wd\SDSSJ022058.67-022737.0_15047-59230-0299_43...      WD
70    cb_uvex2\SDSSJ103832.01+364910.9_15291-59350-0...      WD
91    wd\SDSSJ054227.06+181533.6_15100-59204-0124_45...      WD
142   wd\SDSSJ074008.41+181046.5_15073-59212-0379_45...      WD
174   wd\SDSSJ081501.29+240052.8_15053-59230-0289_45...      WD
219   wd\SDSSJ081055.11+280825.6_15024-59254-0209_45...      WD
296   wd\SDSSJ174901.53+031807.0_15344-59302-0220_51...      WD
364   wd\SDSSJ113306.34+570357.3_15235-59281-0171_43...      WD
418   cb_uvex2\SDSSJ081540.72+391056.9_15026-59169-0...      WD
428   wd\SDSSJ072300.38-253119.9_15116-59220-0035_44...      WD
443   wd\SDSSJ133424.20+400928.4_15299-59293-0186_46...      WD
463   wd\SDSSJ134908.51-043940.4_15200-59324-0218_45...      WD
505   wd\SDSSJ144009.67+043734.5_15306-59347-0204_46...      WD
511   wd\SDSSJ235127.91+005725.5_15034-59165-0334_43...      WD
544   wd\SDSSJ090200.26+503722.0_15174-59284-0259_43...      WD
587   wd\SDSSJ093906.50+035435.5_15270-59284-0238_45...      WD
678   wd\SDSSJ060818.77+020455.8_15227-59264-0200_45...      WD
734   wd\SDSSJ143534.16+043425.6_15306-59315-0470_46...      WD
778   wd\SDSSJ083912.73+014820.9_15255-59279-0274_45...      WD
783   wd\SDSSJ061620.21+032034.7_15137-59214-0101_45...      WD
797   wd\SDSSJ123750.88+141055.4_15355-59359-0118_45...      WD
915   wd\SDSSJ111109.23+384856.2_15352-59358-0436_45...      WD
935   wd\SDSSJ135258.71+265853.6_15301-59338-0004_46...      WD
938   wd\SDSSJ184905.45+372555.9_15332-59305-0161_53...      WD
957   wd\SDSSJ003725.45+005208.7_15005-59167-0265_43...      WD
989   wd\SDSSJ135041.47-044329.4_15200-59324-0097_45...      WD
1026  cb_uvex2\SDSSJ072349.92+241658.5_15285-59276-0...      WD

In [11]:
only_wd.to_csv(os.path.join(current_dir, 'only_wd.csv'))

Now we can create the config file

In [12]:
import configparser

config = configparser.ConfigParser()

config.add_section('models')
config['models']['class_model'] = 'models/model_4C_3FC.h5'
config['models']['dom_model'] = 'models/rf_best_model.joblib'

config.add_section('paths')
config['paths']['data_path'] = 'C:/Users/jotab/Documents/Github/sdss_repo/scripts/only_wd.csv'
config['paths']['save_path'] = 'D:/SDSS_Results'
config['paths']['relative_path'] = 'C:/Users/jotab/Documents/Github/sdss_repo/data/raw/sdss_dat_files'

with open("default_config.ini", 'w') as f:
    config.write(f)

Analyze results